pipeline:
  amd64:
    image: plugins/docker
    registry: no-cloud.fr
    repo: no-cloud.fr/amd64/multiarch
    tag: latest
    dockerfile: Dockerfile.amd64
  arm32v7:
    image: plugins/docker
    registry: no-cloud.fr
    repo: no-cloud.fr/arm/multiarch
    tag: latest
    dockerfile: Dockerfile.arm32v7
  manifest:
    image: plugins/manifest
    username: osef
    password: osef
    target: no-cloud.fr/multiarch
    template: no-cloud-fr/ARCH/multiarch
    platforms:
      - linux/amd64
      - linux/arm

